using System;

public enum VisualEffectType
{
    None,
    CardWinBoon,
    CardWinBoonDeck,
    CardWinEnemy,
    CardWinEnemyFire,
    CardWinEnemyForce,
    CardWinEnemyAcid,
    CardWinEnemyCold,
    CardWinEnemyPoison,
    CardWinEnemyElectricity,
    CardWinEnemyMental,
    CardWinEnemyMeleeBlunt,
    CardWinEnemyRangedPiercing,
    CardWinEnemyLiquid,
    CardLoseEnemy,
    CardLoseEnemyFire,
    CardLoseEnemyForce,
    CardLoseEnemyAcid,
    CardLoseEnemyCold,
    CardLoseEnemyPoison,
    CardLoseEnemyElectricity,
    CardLoseEnemyMental,
    CardLoseEnemyMeleePiercing,
    CardLoseEnemyMeleeBlunt,
    CardLoseEnemyRangedPiercing,
    CardLoseEnemyRangedBlunt,
    CardUndefeated,
    CardUndefeatedGhost,
    CardBanishToBox,
    CardBanishFromDisplay,
    CardBanishFromDiscard,
    CardSummonFromBox,
    GlowSpecial,
    CardWinBoonSetAside,
    CardDefeatedBanish,
    CardSalvage,
    CardRestrictStart,
    CardRestrictStop
}

